import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, writeFileSync, rmSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { mkTmpRepo } from './helpers.js';
import { mint, recordGate } from '../lib/slices.js';
import { writeYaml } from '../lib/core.js';
import { buildIndex, writeIndex, status, next, renderDevState } from '../lib/derive.js';

function seed() {
  const repo = mkTmpRepo();
  const id = mint(repo, 'OOM fix', {});
  writeYaml(join(repo, `docs/slices/${id}/tasks.yaml`), { tasks: [
    { id: 't1', title: 'a', state: 'done', verify: 'true', depends_on: [], evidence: { cmd: 'true', cmd_exit: 0, at: 'x' } },
    { id: 't2', title: 'b', state: 'todo', verify: 'true', depends_on: ['t1'] },
    { id: 't3', title: 'c', state: 'todo', verify: 'true', depends_on: ['t2'] },
    { id: 't4', title: 'd', state: 'skipped', skip_reason: 'obsolete', depends_on: [] } ] });
  recordGate(repo, 'plan_check', { slice: id, verdict: 'GO', by: 'agent' });
  return { repo, id };
}

test('index: aggregates manifests + tasks + gates; deterministic (delete + rebuild == identical)', () => {
  const { repo, id } = seed();
  writeIndex(repo);
  const a = readFileSync(join(repo, '.house/index.json'), 'utf8');
  rmSync(join(repo, '.house/index.json'));
  writeIndex(repo);
  assert.equal(readFileSync(join(repo, '.house/index.json'), 'utf8'), a);   // THE kernel invariant
  const idx = JSON.parse(a);
  assert.equal(idx.slices[0].id, id);
  assert.equal(idx.slices[0].progress.done, 1);
  assert.equal(idx.slices[0].progress.total, 3);                            // skipped leaves the denominator
  assert.equal(idx.slices[0].gates.plan_check, 'GO');
  // fixed key set — a generated_at/timestamp field would both break rebuild-determinism and fail this
  assert.deepEqual(Object.keys(idx.slices[0]).sort(),
    ['blocked_on', 'branch', 'gates', 'id', 'kind', 'pr', 'progress', 'rigor', 'state', 'tasks', 'title', 'units'].sort());
});

test('next: ready set = todo tasks with all depends_on done', () => {
  const { repo } = seed();
  const ready = JSON.parse(next(repo, { json: true }));
  assert.deepEqual(ready.map(t => t.id), ['t2']);                           // t3 waits on t2
});

test('status --json: one line per slice with state + progress', () => {
  const { repo, id } = seed();
  const s = JSON.parse(status(repo, { json: true }));
  assert.equal(s.slices[0].id, id);
  assert.equal(s.slices[0].state, 'shaping');
});

test('render dev-state: generated top from index; hand-authored block between markers preserved', () => {
  const { repo, id } = seed();
  const dsPath = join(repo, 'docs/dev-state.md');
  writeFileSync(dsPath, ['# x — dev state', '', '<!-- house:manual -->', '## Gotchas', '- editing repo file IS the live skill',
    '<!-- /house:manual -->', ''].join('\n'));
  renderDevState(repo);
  const out = readFileSync(dsPath, 'utf8');
  assert.match(out, new RegExp(`## Active\\b[\\s\\S]*${id}`));       // generated section lists the slice
  assert.match(out, /## In-flight/);                                 // all four doctrine sections render
  assert.match(out, /editing repo file IS the live skill/);          // manual block survived
  renderDevState(repo);                                              // idempotent
  assert.equal(readFileSync(dsPath, 'utf8'), out);
});

test('render dev-state: REFUSES when hand-authored content sits outside the manual markers (no silent drops)', () => {
  const { repo } = seed();
  writeFileSync(join(repo, 'docs/dev-state.md'), '# x — dev state\n\n## Rogue hand section\n- precious content\n');
  assert.throws(() => renderDevState(repo), /outside .* markers/);
});

test('render dev-state: REFUSES content appended AFTER the manual markers on an already-rendered file', () => {
  // the likeliest real sequence: render once, then hand-append below the closing marker.
  const { repo } = seed();
  const dsPath = join(repo, 'docs/dev-state.md');
  writeFileSync(dsPath, '# x — dev state\n\n<!-- house:manual -->\n## Gotchas\n- kept\n<!-- /house:manual -->\n');
  renderDevState(repo);                                              // now the file has a generated block
  writeFileSync(dsPath, readFileSync(dsPath, 'utf8') + '\n## PRECIOUS HAND SECTION\n- irreplaceable\n');
  assert.throws(() => renderDevState(repo), /outside .* markers/);
  assert.match(readFileSync(dsPath, 'utf8'), /PRECIOUS HAND SECTION/);  // and it is still on disk
});

test('render dev-state: REFUSES content wedged between the title and the generated block', () => {
  const { repo } = seed();
  const dsPath = join(repo, 'docs/dev-state.md');
  writeFileSync(dsPath, '# x — dev state\n\n<!-- house:manual -->\n- kept\n<!-- /house:manual -->\n');
  renderDevState(repo);
  const cur = readFileSync(dsPath, 'utf8');
  writeFileSync(dsPath, cur.replace('<!-- generated by', '## Wedged in\n- also precious\n\n<!-- generated by'));
  assert.throws(() => renderDevState(repo), /outside .* markers/);
});

test('index/status/next/render survive a tasks.yaml with no tasks: key (shaper placeholder)', () => {
  const { repo, id } = seed();
  writeFileSync(join(repo, `docs/slices/${id}/tasks.yaml`), '# placeholder written at handoff\n');
  const idx = buildIndex(repo);                                      // must not throw
  assert.deepEqual(idx.slices[0].progress, { done: 0, total: 0 });
  assert.deepEqual(JSON.parse(next(repo, { json: true })), []);
  assert.doesNotThrow(() => JSON.parse(status(repo, { json: true })));
  writeFileSync(join(repo, 'docs/dev-state.md'), '# t\n\n<!-- house:manual -->\n<!-- /house:manual -->\n');
  assert.doesNotThrow(() => renderDevState(repo));
});

test('index: a stray non-YAML file in gates/ does not take down the derived layer', () => {
  const { repo, id } = seed();
  writeFileSync(join(repo, `docs/slices/${id}/gates/.DS_Store`), 'binary-ish junk');
  const idx = buildIndex(repo);
  assert.deepEqual(Object.keys(idx.slices[0].gates), ['plan_check']);
});

test('index: slice dirs and gate files are sorted, and the top level has a fixed key set', () => {
  const { repo } = seed();
  const b = mint(repo, 'zzz last', {});
  recordGate(repo, 'spec_review', { slice: b, verdict: 'approved', by: 'human' });
  recordGate(repo, 'merge_gate', { slice: b, verdict: 'GO', by: 'agent' });
  const idx = buildIndex(repo);
  assert.deepEqual(Object.keys(idx), ['schema_version', 'slices']);         // no generated_at
  assert.deepEqual(idx.slices.map(s => s.id), [...idx.slices.map(s => s.id)].sort());
  assert.deepEqual(Object.keys(idx.slices[1].gates), ['merge_gate', 'spec_review']);   // sorted, not readdir order
});
