import { readdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { readYaml } from './core.js';

export function buildIndex(root) {
  const dir = join(root, 'docs/slices');
  const slices = (existsSync(dir) ? readdirSync(dir) : [])
    .filter(d => existsSync(join(dir, d, 'slice.yaml'))).sort()
    .map(d => {
      const man = readYaml(join(dir, d, 'slice.yaml'));
      const tasksFile = join(dir, d, 'tasks.yaml');
      // a placeholder tasks.yaml (empty, or written without a `tasks:` key) must not take down
      // index/status/next/render — the shaper authors this file at handoff
      const tasks = (existsSync(tasksFile) ? readYaml(tasksFile)?.tasks : null) ?? [];
      const counted = tasks.filter(t => t.state !== 'skipped');
      const gatesDir = join(dir, d, 'gates');
      const gates = {};
      if (existsSync(gatesDir)) for (const g of readdirSync(gatesDir).filter(f => f.endsWith('.yaml')).sort())
        gates[g.replace(/\.yaml$/, '')] = readYaml(join(gatesDir, g))?.verdict ?? null;
      return { id: man.id, title: man.title, kind: man.kind, rigor: man.rigor, state: man.state,
        blocked_on: man.blocked_on, branch: man.branch, pr: man.pr, units: man.units ?? [],
        progress: { done: counted.filter(t => t.state === 'done').length, total: counted.length },
        gates, tasks };
    });
  return { schema_version: 1, slices };
}
export function writeIndex(root) {
  writeFileSync(join(root, '.house/index.json'), JSON.stringify(buildIndex(root), null, 2) + '\n');
}
export function status(root, args) {
  const idx = buildIndex(root);
  if (args.json) return JSON.stringify({ slices: idx.slices.map(({ tasks, ...s }) => s) }, null, 2);
  return idx.slices.map(s => `${s.id}  [${s.state}]  ${s.progress.done}/${s.progress.total}  ${s.title}` +
    (s.blocked_on ? `  ⛔ ${s.blocked_on.gate ?? s.blocked_on}` : '')).join('\n') || '(no slices)';
}
export const list = status;                        // same projection; list keeps tasks out either way
export function next(root, args) {
  const idx = buildIndex(root);
  const ready = idx.slices.flatMap(s => (s.tasks ?? [])
    .filter(t => t.state === 'todo' && (t.depends_on ?? []).every(d => s.tasks.find(x => x.id === d)?.state === 'done'))
    .map(t => ({ slice: s.id, id: t.id, title: t.title })));
  return args.json ? JSON.stringify(ready, null, 2) : ready.map(t => `${t.slice} ${t.id} ${t.title}`).join('\n') || '(nothing ready)';
}

export function renderDevState(root) {
  const idx = buildIndex(root);
  const active = idx.slices.filter(s => ['shaping', 'ready', 'building', 'gating', 'live_check'].includes(s.state));
  const slated = idx.slices.filter(s => s.state === 'idea');
  const done = idx.slices.filter(s => s.state === 'shipped');
  const line = (s) => `- **${s.id}** — ${s.title} · state: ${s.state} · ${s.progress.done}/${s.progress.total}` +
    (s.blocked_on ? ` · ⛔ blocked on ${s.blocked_on.gate ?? s.blocked_on}` : '');
  const inflight = idx.slices.filter(s => s.pr != null || (s.units ?? []).some(u => u.state === 'building'));
  const gen = ['<!-- generated by `house render dev-state` — do not hand-edit above the manual marker -->',
    '## Active', ...(active.length ? active.map(line) : ['- none']),
    '## In-flight', ...(inflight.length ? inflight.map(s => `- **${s.id}** — PR ${s.pr ?? 'n/a'}`) : ['- none']),
    '## Slated', ...(slated.length ? slated.map(line) : ['- none']),
    '## Done', ...(done.length ? done.map(line) : ['- none']), ''].join('\n');
  const dsPath = join(root, 'docs/dev-state.md');
  const cur = existsSync(dsPath) ? readFileSync(dsPath, 'utf8') : '';
  const m = /<!-- house:manual -->[\s\S]*?<!-- \/house:manual -->/.exec(cur);
  const manual = m ? m[0] : '<!-- house:manual -->\n<!-- /house:manual -->';
  const title = /^# .*$/m.exec(cur)?.[0] ?? '# dev state';
  // Refuse silent data loss: content outside title / generated block / manual markers must be wrapped first.
  // ORDER MATTERS — strip the generated block while the opening manual marker is still present, so its
  // lookahead anchors on that marker. Removing the manual block first would leave the lazy match with only
  // `$` to stop at, swallowing (and silently dropping) everything after `<!-- /house:manual -->`.
  const leftover = cur
    .replace(/<!-- generated by[\s\S]*?(?=<!-- house:manual -->|$)/, '')
    .replace(m?.[0] ?? '', '')
    .replace(/^# .*$/m, '')
    .trim();
  if (leftover)
    throw new Error('dev-state.md has content outside the <!-- house:manual --> markers — wrap it first (no silent drops)');
  writeFileSync(dsPath, `${title}\n\n${gen}\n${manual}\n`);
}
